/**
 * AVIF/WebP sibling paths for LOCAL pre-optimised imagery.
 *
 * Every local photo in /public ships as a .avif + .webp next to its source
 * raster, generated by scripts/export-formats.mjs. These helpers just swap the
 * file extension — same directory, same basename — so a component can point at
 * one base path (e.g. "/lifestyle/neck-shoulders.png") and derive the formats
 * a browser should be offered in order (AVIF first, WebP second, source as the
 * last-resort <img> src). Same trick components/product/EraExplorer.tsx does
 * inline with its .webp/.avif pair, factored out for the shared picture
 * component.
 */
const FORMAT_EXT = /\.(avif|webp|png|jpe?g)$/i;

function swapFormat(src: string, ext: "avif" | "webp"): string {
  return src.replace(FORMAT_EXT, `.${ext}`);
}

/** Same-named .avif sibling — the preferred format, offer it first. */
export function avifSrc(src: string): string {
  return swapFormat(src, "avif");
}

/** Same-named .webp sibling — the broadly-supported fallback. */
export function webpSrc(src: string): string {
  return swapFormat(src, "webp");
}
